name: save_to_folder_ios_example
description: "Demonstrates how to use the save_to_folder_ios plugin."
publish_to: 'none' 

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  save_to_folder_ios:
    path: ../
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
 